### PR TITLE
Force https for www.resourcedata.org

### PR DESCRIPTION
**Pull request by iprunache**
Updated the nginx config to redirect all http users to https. It also redirects resourcedata.org to the canonical www.resourcedata.org.

### CODE REVIEW

**Comment by iprunache** [comment]
@mattfullerton do you have any concerns about changing the nginx config specifically for resourcedata? Ideally I wouldn't have hardcoded the domain in the config but couldn't find an easier way of doing that redirect on both http and https.

**Comment by mattfullerton** [comment]
It doesn't concern me as such, the only annoyance is that I now had to finally switch to maintaining production and staging branches locally as the nginx conf is different for each (?). But that would have been inevitable anyway.

**Comment by iprunache** [comment]
We consider the staging branch dispensable on most of our projects. If you need staging and production to match, just delete staging and cut it again from master.

I used it to test partial changes on the staging env so maybe that's why it's different but feel free to redo the branch.

**Comment by mattfullerton** [comment]
Do we not have different text now on both for the nginx config if the domain name is in there?

**Comment by iprunache** [comment]
The only domain name there is `resourcedata.org` that needs to be redirected to `www.resourcedata.org` and its ok to be both on prod and staging.

The default server config is a catchall, `_`, and uses `$host` to reference the domain when doing the redirect from `http` to `https` so the config is the same across branches.

Perhaps it would be better to replace the `_` with `*.resourcedata.org` to prevent other domains from working but that wouldn't change things much.

**Pull request merged**
